//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.08 at 09:21:29 PM MSK 
//


package hello.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hello.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hello.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnumBICXMLResponse }
     * 
     */
    public EnumBICXMLResponse createEnumBICXMLResponse() {
        return new EnumBICXMLResponse();
    }

    /**
     * Create an instance of {@link EnumBICResponse }
     * 
     */
    public EnumBICResponse createEnumBICResponse() {
        return new EnumBICResponse();
    }

    /**
     * Create an instance of {@link Data101FormExXMLResponse }
     * 
     */
    public Data101FormExXMLResponse createData101FormExXMLResponse() {
        return new Data101FormExXMLResponse();
    }

    /**
     * Create an instance of {@link Data101FormExResponse }
     * 
     */
    public Data101FormExResponse createData101FormExResponse() {
        return new Data101FormExResponse();
    }

    /**
     * Create an instance of {@link Data101FormXMLResponse }
     * 
     */
    public Data101FormXMLResponse createData101FormXMLResponse() {
        return new Data101FormXMLResponse();
    }

    /**
     * Create an instance of {@link Data101FormResponse }
     * 
     */
    public Data101FormResponse createData101FormResponse() {
        return new Data101FormResponse();
    }

    /**
     * Create an instance of {@link Data101FullXMLResponse }
     * 
     */
    public Data101FullXMLResponse createData101FullXMLResponse() {
        return new Data101FullXMLResponse();
    }

    /**
     * Create an instance of {@link Data101FullExXMLResponse }
     * 
     */
    public Data101FullExXMLResponse createData101FullExXMLResponse() {
        return new Data101FullExXMLResponse();
    }

    /**
     * Create an instance of {@link Data101FullExResponse }
     * 
     */
    public Data101FullExResponse createData101FullExResponse() {
        return new Data101FullExResponse();
    }

    /**
     * Create an instance of {@link Data101FullExV2XMLResponse }
     * 
     */
    public Data101FullExV2XMLResponse createData101FullExV2XMLResponse() {
        return new Data101FullExV2XMLResponse();
    }

    /**
     * Create an instance of {@link Data101FullExV2Response }
     * 
     */
    public Data101FullExV2Response createData101FullExV2Response() {
        return new Data101FullExV2Response();
    }

    /**
     * Create an instance of {@link Data101FullResponse }
     * 
     */
    public Data101FullResponse createData101FullResponse() {
        return new Data101FullResponse();
    }

    /**
     * Create an instance of {@link Data101FullV2XMLResponse }
     * 
     */
    public Data101FullV2XMLResponse createData101FullV2XMLResponse() {
        return new Data101FullV2XMLResponse();
    }

    /**
     * Create an instance of {@link Data101FullV2Response }
     * 
     */
    public Data101FullV2Response createData101FullV2Response() {
        return new Data101FullV2Response();
    }

    /**
     * Create an instance of {@link Data102FormExXMLResponse }
     * 
     */
    public Data102FormExXMLResponse createData102FormExXMLResponse() {
        return new Data102FormExXMLResponse();
    }

    /**
     * Create an instance of {@link Data102FormExResponse }
     * 
     */
    public Data102FormExResponse createData102FormExResponse() {
        return new Data102FormExResponse();
    }

    /**
     * Create an instance of {@link Data102FormXMLResponse }
     * 
     */
    public Data102FormXMLResponse createData102FormXMLResponse() {
        return new Data102FormXMLResponse();
    }

    /**
     * Create an instance of {@link Data102FormResponse }
     * 
     */
    public Data102FormResponse createData102FormResponse() {
        return new Data102FormResponse();
    }

    /**
     * Create an instance of {@link Form102IndicatorsEnumXMLResponse }
     * 
     */
    public Form102IndicatorsEnumXMLResponse createForm102IndicatorsEnumXMLResponse() {
        return new Form102IndicatorsEnumXMLResponse();
    }

    /**
     * Create an instance of {@link Form102IndicatorsEnumResponse }
     * 
     */
    public Form102IndicatorsEnumResponse createForm102IndicatorsEnumResponse() {
        return new Form102IndicatorsEnumResponse();
    }

    /**
     * Create an instance of {@link Form101IndicatorsEnumXMLResponse }
     * 
     */
    public Form101IndicatorsEnumXMLResponse createForm101IndicatorsEnumXMLResponse() {
        return new Form101IndicatorsEnumXMLResponse();
    }

    /**
     * Create an instance of {@link Form101IndicatorsEnumResponse }
     * 
     */
    public Form101IndicatorsEnumResponse createForm101IndicatorsEnumResponse() {
        return new Form101IndicatorsEnumResponse();
    }

    /**
     * Create an instance of {@link RegionsEnumResponse }
     * 
     */
    public RegionsEnumResponse createRegionsEnumResponse() {
        return new RegionsEnumResponse();
    }

    /**
     * Create an instance of {@link RegionsEnumXMLResponse }
     * 
     */
    public RegionsEnumXMLResponse createRegionsEnumXMLResponse() {
        return new RegionsEnumXMLResponse();
    }

    /**
     * Create an instance of {@link SearchByRegionCodeResponse }
     * 
     */
    public SearchByRegionCodeResponse createSearchByRegionCodeResponse() {
        return new SearchByRegionCodeResponse();
    }

    /**
     * Create an instance of {@link SearchByRegionCodeXMLResponse }
     * 
     */
    public SearchByRegionCodeXMLResponse createSearchByRegionCodeXMLResponse() {
        return new SearchByRegionCodeXMLResponse();
    }

    /**
     * Create an instance of {@link SearchByNameXMLResponse }
     * 
     */
    public SearchByNameXMLResponse createSearchByNameXMLResponse() {
        return new SearchByNameXMLResponse();
    }

    /**
     * Create an instance of {@link SearchByNameResponse }
     * 
     */
    public SearchByNameResponse createSearchByNameResponse() {
        return new SearchByNameResponse();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeXMLResponse }
     * 
     */
    public CreditInfoByIntCodeXMLResponse createCreditInfoByIntCodeXMLResponse() {
        return new CreditInfoByIntCodeXMLResponse();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeExXMLResponse }
     * 
     */
    public CreditInfoByIntCodeExXMLResponse createCreditInfoByIntCodeExXMLResponse() {
        return new CreditInfoByIntCodeExXMLResponse();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeExResponse }
     * 
     */
    public CreditInfoByIntCodeExResponse createCreditInfoByIntCodeExResponse() {
        return new CreditInfoByIntCodeExResponse();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeResponse }
     * 
     */
    public CreditInfoByIntCodeResponse createCreditInfoByIntCodeResponse() {
        return new CreditInfoByIntCodeResponse();
    }

    /**
     * Create an instance of {@link GetOfficesResponse }
     * 
     */
    public GetOfficesResponse createGetOfficesResponse() {
        return new GetOfficesResponse();
    }

    /**
     * Create an instance of {@link GetOfficesByRegionResponse }
     * 
     */
    public GetOfficesByRegionResponse createGetOfficesByRegionResponse() {
        return new GetOfficesByRegionResponse();
    }

    /**
     * Create an instance of {@link GetOfficesXMLResponse }
     * 
     */
    public GetOfficesXMLResponse createGetOfficesXMLResponse() {
        return new GetOfficesXMLResponse();
    }

    /**
     * Create an instance of {@link GetOfficesByRegionXMLResponse }
     * 
     */
    public GetOfficesByRegionXMLResponse createGetOfficesByRegionXMLResponse() {
        return new GetOfficesByRegionXMLResponse();
    }

    /**
     * Create an instance of {@link Data134FormFullXMLResponse }
     * 
     */
    public Data134FormFullXMLResponse createData134FormFullXMLResponse() {
        return new Data134FormFullXMLResponse();
    }

    /**
     * Create an instance of {@link Olap134FormResponse }
     * 
     */
    public Olap134FormResponse createOlap134FormResponse() {
        return new Olap134FormResponse();
    }

    /**
     * Create an instance of {@link Data135FormFullResponse }
     * 
     */
    public Data135FormFullResponse createData135FormFullResponse() {
        return new Data135FormFullResponse();
    }

    /**
     * Create an instance of {@link Data135FormFullXMLResponse }
     * 
     */
    public Data135FormFullXMLResponse createData135FormFullXMLResponse() {
        return new Data135FormFullXMLResponse();
    }

    /**
     * Create an instance of {@link Data123FormFullResponse }
     * 
     */
    public Data123FormFullResponse createData123FormFullResponse() {
        return new Data123FormFullResponse();
    }

    /**
     * Create an instance of {@link Data123FormFullXMLResponse }
     * 
     */
    public Data123FormFullXMLResponse createData123FormFullXMLResponse() {
        return new Data123FormFullXMLResponse();
    }

    /**
     * Create an instance of {@link Data134FormFullResponse }
     * 
     */
    public Data134FormFullResponse createData134FormFullResponse() {
        return new Data134FormFullResponse();
    }

    /**
     * Create an instance of {@link EnumBICXML }
     * 
     */
    public EnumBICXML createEnumBICXML() {
        return new EnumBICXML();
    }

    /**
     * Create an instance of {@link EnumBICXMLResponse.EnumBICXMLResult }
     * 
     */
    public EnumBICXMLResponse.EnumBICXMLResult createEnumBICXMLResponseEnumBICXMLResult() {
        return new EnumBICXMLResponse.EnumBICXMLResult();
    }

    /**
     * Create an instance of {@link GetFormsMaxDate }
     * 
     */
    public GetFormsMaxDate createGetFormsMaxDate() {
        return new GetFormsMaxDate();
    }

    /**
     * Create an instance of {@link GetFormsMaxDateResponse }
     * 
     */
    public GetFormsMaxDateResponse createGetFormsMaxDateResponse() {
        return new GetFormsMaxDateResponse();
    }

    /**
     * Create an instance of {@link LastUpdate }
     * 
     */
    public LastUpdate createLastUpdate() {
        return new LastUpdate();
    }

    /**
     * Create an instance of {@link LastUpdateResponse }
     * 
     */
    public LastUpdateResponse createLastUpdateResponse() {
        return new LastUpdateResponse();
    }

    /**
     * Create an instance of {@link EnumBIC }
     * 
     */
    public EnumBIC createEnumBIC() {
        return new EnumBIC();
    }

    /**
     * Create an instance of {@link EnumBICResponse.EnumBICResult }
     * 
     */
    public EnumBICResponse.EnumBICResult createEnumBICResponseEnumBICResult() {
        return new EnumBICResponse.EnumBICResult();
    }

    /**
     * Create an instance of {@link Data101FormExXML }
     * 
     */
    public Data101FormExXML createData101FormExXML() {
        return new Data101FormExXML();
    }

    /**
     * Create an instance of {@link ArrayOfAnyType }
     * 
     */
    public ArrayOfAnyType createArrayOfAnyType() {
        return new ArrayOfAnyType();
    }

    /**
     * Create an instance of {@link Data101FormExXMLResponse.Data101FormExXMLResult }
     * 
     */
    public Data101FormExXMLResponse.Data101FormExXMLResult createData101FormExXMLResponseData101FormExXMLResult() {
        return new Data101FormExXMLResponse.Data101FormExXMLResult();
    }

    /**
     * Create an instance of {@link Data101FormEx }
     * 
     */
    public Data101FormEx createData101FormEx() {
        return new Data101FormEx();
    }

    /**
     * Create an instance of {@link Data101FormExResponse.Data101FormExResult }
     * 
     */
    public Data101FormExResponse.Data101FormExResult createData101FormExResponseData101FormExResult() {
        return new Data101FormExResponse.Data101FormExResult();
    }

    /**
     * Create an instance of {@link Data101FormXML }
     * 
     */
    public Data101FormXML createData101FormXML() {
        return new Data101FormXML();
    }

    /**
     * Create an instance of {@link Data101FormXMLResponse.Data101FormXMLResult }
     * 
     */
    public Data101FormXMLResponse.Data101FormXMLResult createData101FormXMLResponseData101FormXMLResult() {
        return new Data101FormXMLResponse.Data101FormXMLResult();
    }

    /**
     * Create an instance of {@link Data101Form }
     * 
     */
    public Data101Form createData101Form() {
        return new Data101Form();
    }

    /**
     * Create an instance of {@link Data101FormResponse.Data101FormResult }
     * 
     */
    public Data101FormResponse.Data101FormResult createData101FormResponseData101FormResult() {
        return new Data101FormResponse.Data101FormResult();
    }

    /**
     * Create an instance of {@link Data101FullXML }
     * 
     */
    public Data101FullXML createData101FullXML() {
        return new Data101FullXML();
    }

    /**
     * Create an instance of {@link Data101FullXMLResponse.Data101FullXMLResult }
     * 
     */
    public Data101FullXMLResponse.Data101FullXMLResult createData101FullXMLResponseData101FullXMLResult() {
        return new Data101FullXMLResponse.Data101FullXMLResult();
    }

    /**
     * Create an instance of {@link Data101FullExXML }
     * 
     */
    public Data101FullExXML createData101FullExXML() {
        return new Data101FullExXML();
    }

    /**
     * Create an instance of {@link Data101FullExXMLResponse.Data101FullExXMLResult }
     * 
     */
    public Data101FullExXMLResponse.Data101FullExXMLResult createData101FullExXMLResponseData101FullExXMLResult() {
        return new Data101FullExXMLResponse.Data101FullExXMLResult();
    }

    /**
     * Create an instance of {@link Data101FullEx }
     * 
     */
    public Data101FullEx createData101FullEx() {
        return new Data101FullEx();
    }

    /**
     * Create an instance of {@link Data101FullExResponse.Data101FullExResult }
     * 
     */
    public Data101FullExResponse.Data101FullExResult createData101FullExResponseData101FullExResult() {
        return new Data101FullExResponse.Data101FullExResult();
    }

    /**
     * Create an instance of {@link Data101FullExV2XML }
     * 
     */
    public Data101FullExV2XML createData101FullExV2XML() {
        return new Data101FullExV2XML();
    }

    /**
     * Create an instance of {@link Data101FullExV2XMLResponse.Data101FullExV2XMLResult }
     * 
     */
    public Data101FullExV2XMLResponse.Data101FullExV2XMLResult createData101FullExV2XMLResponseData101FullExV2XMLResult() {
        return new Data101FullExV2XMLResponse.Data101FullExV2XMLResult();
    }

    /**
     * Create an instance of {@link Data101FullExV2 }
     * 
     */
    public Data101FullExV2 createData101FullExV2() {
        return new Data101FullExV2();
    }

    /**
     * Create an instance of {@link Data101FullExV2Response.Data101FullExV2Result }
     * 
     */
    public Data101FullExV2Response.Data101FullExV2Result createData101FullExV2ResponseData101FullExV2Result() {
        return new Data101FullExV2Response.Data101FullExV2Result();
    }

    /**
     * Create an instance of {@link Data101Full }
     * 
     */
    public Data101Full createData101Full() {
        return new Data101Full();
    }

    /**
     * Create an instance of {@link Data101FullResponse.Data101FullResult }
     * 
     */
    public Data101FullResponse.Data101FullResult createData101FullResponseData101FullResult() {
        return new Data101FullResponse.Data101FullResult();
    }

    /**
     * Create an instance of {@link Data101FullV2XML }
     * 
     */
    public Data101FullV2XML createData101FullV2XML() {
        return new Data101FullV2XML();
    }

    /**
     * Create an instance of {@link Data101FullV2XMLResponse.Data101FullV2XMLResult }
     * 
     */
    public Data101FullV2XMLResponse.Data101FullV2XMLResult createData101FullV2XMLResponseData101FullV2XMLResult() {
        return new Data101FullV2XMLResponse.Data101FullV2XMLResult();
    }

    /**
     * Create an instance of {@link Data101FullV2 }
     * 
     */
    public Data101FullV2 createData101FullV2() {
        return new Data101FullV2();
    }

    /**
     * Create an instance of {@link Data101FullV2Response.Data101FullV2Result }
     * 
     */
    public Data101FullV2Response.Data101FullV2Result createData101FullV2ResponseData101FullV2Result() {
        return new Data101FullV2Response.Data101FullV2Result();
    }

    /**
     * Create an instance of {@link Data102FormExXML }
     * 
     */
    public Data102FormExXML createData102FormExXML() {
        return new Data102FormExXML();
    }

    /**
     * Create an instance of {@link Data102FormExXMLResponse.Data102FormExXMLResult }
     * 
     */
    public Data102FormExXMLResponse.Data102FormExXMLResult createData102FormExXMLResponseData102FormExXMLResult() {
        return new Data102FormExXMLResponse.Data102FormExXMLResult();
    }

    /**
     * Create an instance of {@link Data102FormEx }
     * 
     */
    public Data102FormEx createData102FormEx() {
        return new Data102FormEx();
    }

    /**
     * Create an instance of {@link Data102FormExResponse.Data102FormExResult }
     * 
     */
    public Data102FormExResponse.Data102FormExResult createData102FormExResponseData102FormExResult() {
        return new Data102FormExResponse.Data102FormExResult();
    }

    /**
     * Create an instance of {@link Data102FormXML }
     * 
     */
    public Data102FormXML createData102FormXML() {
        return new Data102FormXML();
    }

    /**
     * Create an instance of {@link Data102FormXMLResponse.Data102FormXMLResult }
     * 
     */
    public Data102FormXMLResponse.Data102FormXMLResult createData102FormXMLResponseData102FormXMLResult() {
        return new Data102FormXMLResponse.Data102FormXMLResult();
    }

    /**
     * Create an instance of {@link Data102Form }
     * 
     */
    public Data102Form createData102Form() {
        return new Data102Form();
    }

    /**
     * Create an instance of {@link Data102FormResponse.Data102FormResult }
     * 
     */
    public Data102FormResponse.Data102FormResult createData102FormResponseData102FormResult() {
        return new Data102FormResponse.Data102FormResult();
    }

    /**
     * Create an instance of {@link Form102IndicatorsEnumXML }
     * 
     */
    public Form102IndicatorsEnumXML createForm102IndicatorsEnumXML() {
        return new Form102IndicatorsEnumXML();
    }

    /**
     * Create an instance of {@link Form102IndicatorsEnumXMLResponse.Form102IndicatorsEnumXMLResult }
     * 
     */
    public Form102IndicatorsEnumXMLResponse.Form102IndicatorsEnumXMLResult createForm102IndicatorsEnumXMLResponseForm102IndicatorsEnumXMLResult() {
        return new Form102IndicatorsEnumXMLResponse.Form102IndicatorsEnumXMLResult();
    }

    /**
     * Create an instance of {@link Form102IndicatorsEnum }
     * 
     */
    public Form102IndicatorsEnum createForm102IndicatorsEnum() {
        return new Form102IndicatorsEnum();
    }

    /**
     * Create an instance of {@link Form102IndicatorsEnumResponse.Form102IndicatorsEnumResult }
     * 
     */
    public Form102IndicatorsEnumResponse.Form102IndicatorsEnumResult createForm102IndicatorsEnumResponseForm102IndicatorsEnumResult() {
        return new Form102IndicatorsEnumResponse.Form102IndicatorsEnumResult();
    }

    /**
     * Create an instance of {@link Form101IndicatorsEnumXML }
     * 
     */
    public Form101IndicatorsEnumXML createForm101IndicatorsEnumXML() {
        return new Form101IndicatorsEnumXML();
    }

    /**
     * Create an instance of {@link Form101IndicatorsEnumXMLResponse.Form101IndicatorsEnumXMLResult }
     * 
     */
    public Form101IndicatorsEnumXMLResponse.Form101IndicatorsEnumXMLResult createForm101IndicatorsEnumXMLResponseForm101IndicatorsEnumXMLResult() {
        return new Form101IndicatorsEnumXMLResponse.Form101IndicatorsEnumXMLResult();
    }

    /**
     * Create an instance of {@link Form101IndicatorsEnum }
     * 
     */
    public Form101IndicatorsEnum createForm101IndicatorsEnum() {
        return new Form101IndicatorsEnum();
    }

    /**
     * Create an instance of {@link Form101IndicatorsEnumResponse.Form101IndicatorsEnumResult }
     * 
     */
    public Form101IndicatorsEnumResponse.Form101IndicatorsEnumResult createForm101IndicatorsEnumResponseForm101IndicatorsEnumResult() {
        return new Form101IndicatorsEnumResponse.Form101IndicatorsEnumResult();
    }

    /**
     * Create an instance of {@link RegNumToIntCode }
     * 
     */
    public RegNumToIntCode createRegNumToIntCode() {
        return new RegNumToIntCode();
    }

    /**
     * Create an instance of {@link RegNumToIntCodeResponse }
     * 
     */
    public RegNumToIntCodeResponse createRegNumToIntCodeResponse() {
        return new RegNumToIntCodeResponse();
    }

    /**
     * Create an instance of {@link IntCodeToRegNum }
     * 
     */
    public IntCodeToRegNum createIntCodeToRegNum() {
        return new IntCodeToRegNum();
    }

    /**
     * Create an instance of {@link IntCodeToRegNumResponse }
     * 
     */
    public IntCodeToRegNumResponse createIntCodeToRegNumResponse() {
        return new IntCodeToRegNumResponse();
    }

    /**
     * Create an instance of {@link BicToIntCode }
     * 
     */
    public BicToIntCode createBicToIntCode() {
        return new BicToIntCode();
    }

    /**
     * Create an instance of {@link BicToIntCodeResponse }
     * 
     */
    public BicToIntCodeResponse createBicToIntCodeResponse() {
        return new BicToIntCodeResponse();
    }

    /**
     * Create an instance of {@link BicToRegNumber }
     * 
     */
    public BicToRegNumber createBicToRegNumber() {
        return new BicToRegNumber();
    }

    /**
     * Create an instance of {@link BicToRegNumberResponse }
     * 
     */
    public BicToRegNumberResponse createBicToRegNumberResponse() {
        return new BicToRegNumberResponse();
    }

    /**
     * Create an instance of {@link RegionsEnum }
     * 
     */
    public RegionsEnum createRegionsEnum() {
        return new RegionsEnum();
    }

    /**
     * Create an instance of {@link RegionsEnumResponse.RegionsEnumResult }
     * 
     */
    public RegionsEnumResponse.RegionsEnumResult createRegionsEnumResponseRegionsEnumResult() {
        return new RegionsEnumResponse.RegionsEnumResult();
    }

    /**
     * Create an instance of {@link RegionsEnumXML }
     * 
     */
    public RegionsEnumXML createRegionsEnumXML() {
        return new RegionsEnumXML();
    }

    /**
     * Create an instance of {@link RegionsEnumXMLResponse.RegionsEnumXMLResult }
     * 
     */
    public RegionsEnumXMLResponse.RegionsEnumXMLResult createRegionsEnumXMLResponseRegionsEnumXMLResult() {
        return new RegionsEnumXMLResponse.RegionsEnumXMLResult();
    }

    /**
     * Create an instance of {@link SearchByRegionCode }
     * 
     */
    public SearchByRegionCode createSearchByRegionCode() {
        return new SearchByRegionCode();
    }

    /**
     * Create an instance of {@link SearchByRegionCodeResponse.SearchByRegionCodeResult }
     * 
     */
    public SearchByRegionCodeResponse.SearchByRegionCodeResult createSearchByRegionCodeResponseSearchByRegionCodeResult() {
        return new SearchByRegionCodeResponse.SearchByRegionCodeResult();
    }

    /**
     * Create an instance of {@link SearchByRegionCodeXML }
     * 
     */
    public SearchByRegionCodeXML createSearchByRegionCodeXML() {
        return new SearchByRegionCodeXML();
    }

    /**
     * Create an instance of {@link SearchByRegionCodeXMLResponse.SearchByRegionCodeXMLResult }
     * 
     */
    public SearchByRegionCodeXMLResponse.SearchByRegionCodeXMLResult createSearchByRegionCodeXMLResponseSearchByRegionCodeXMLResult() {
        return new SearchByRegionCodeXMLResponse.SearchByRegionCodeXMLResult();
    }

    /**
     * Create an instance of {@link SearchByNameXML }
     * 
     */
    public SearchByNameXML createSearchByNameXML() {
        return new SearchByNameXML();
    }

    /**
     * Create an instance of {@link SearchByNameXMLResponse.SearchByNameXMLResult }
     * 
     */
    public SearchByNameXMLResponse.SearchByNameXMLResult createSearchByNameXMLResponseSearchByNameXMLResult() {
        return new SearchByNameXMLResponse.SearchByNameXMLResult();
    }

    /**
     * Create an instance of {@link SearchByName }
     * 
     */
    public SearchByName createSearchByName() {
        return new SearchByName();
    }

    /**
     * Create an instance of {@link SearchByNameResponse.SearchByNameResult }
     * 
     */
    public SearchByNameResponse.SearchByNameResult createSearchByNameResponseSearchByNameResult() {
        return new SearchByNameResponse.SearchByNameResult();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeXML }
     * 
     */
    public CreditInfoByIntCodeXML createCreditInfoByIntCodeXML() {
        return new CreditInfoByIntCodeXML();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeXMLResponse.CreditInfoByIntCodeXMLResult }
     * 
     */
    public CreditInfoByIntCodeXMLResponse.CreditInfoByIntCodeXMLResult createCreditInfoByIntCodeXMLResponseCreditInfoByIntCodeXMLResult() {
        return new CreditInfoByIntCodeXMLResponse.CreditInfoByIntCodeXMLResult();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeExXML }
     * 
     */
    public CreditInfoByIntCodeExXML createCreditInfoByIntCodeExXML() {
        return new CreditInfoByIntCodeExXML();
    }

    /**
     * Create an instance of {@link ArrayOfDouble }
     * 
     */
    public ArrayOfDouble createArrayOfDouble() {
        return new ArrayOfDouble();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeExXMLResponse.CreditInfoByIntCodeExXMLResult }
     * 
     */
    public CreditInfoByIntCodeExXMLResponse.CreditInfoByIntCodeExXMLResult createCreditInfoByIntCodeExXMLResponseCreditInfoByIntCodeExXMLResult() {
        return new CreditInfoByIntCodeExXMLResponse.CreditInfoByIntCodeExXMLResult();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeEx }
     * 
     */
    public CreditInfoByIntCodeEx createCreditInfoByIntCodeEx() {
        return new CreditInfoByIntCodeEx();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeExResponse.CreditInfoByIntCodeExResult }
     * 
     */
    public CreditInfoByIntCodeExResponse.CreditInfoByIntCodeExResult createCreditInfoByIntCodeExResponseCreditInfoByIntCodeExResult() {
        return new CreditInfoByIntCodeExResponse.CreditInfoByIntCodeExResult();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCode }
     * 
     */
    public CreditInfoByIntCode createCreditInfoByIntCode() {
        return new CreditInfoByIntCode();
    }

    /**
     * Create an instance of {@link CreditInfoByIntCodeResponse.CreditInfoByIntCodeResult }
     * 
     */
    public CreditInfoByIntCodeResponse.CreditInfoByIntCodeResult createCreditInfoByIntCodeResponseCreditInfoByIntCodeResult() {
        return new CreditInfoByIntCodeResponse.CreditInfoByIntCodeResult();
    }

    /**
     * Create an instance of {@link GetOffices }
     * 
     */
    public GetOffices createGetOffices() {
        return new GetOffices();
    }

    /**
     * Create an instance of {@link GetOfficesResponse.GetOfficesResult }
     * 
     */
    public GetOfficesResponse.GetOfficesResult createGetOfficesResponseGetOfficesResult() {
        return new GetOfficesResponse.GetOfficesResult();
    }

    /**
     * Create an instance of {@link GetOfficesByRegion }
     * 
     */
    public GetOfficesByRegion createGetOfficesByRegion() {
        return new GetOfficesByRegion();
    }

    /**
     * Create an instance of {@link GetOfficesByRegionResponse.GetOfficesByRegionResult }
     * 
     */
    public GetOfficesByRegionResponse.GetOfficesByRegionResult createGetOfficesByRegionResponseGetOfficesByRegionResult() {
        return new GetOfficesByRegionResponse.GetOfficesByRegionResult();
    }

    /**
     * Create an instance of {@link GetOfficesXML }
     * 
     */
    public GetOfficesXML createGetOfficesXML() {
        return new GetOfficesXML();
    }

    /**
     * Create an instance of {@link GetOfficesXMLResponse.GetOfficesXMLResult }
     * 
     */
    public GetOfficesXMLResponse.GetOfficesXMLResult createGetOfficesXMLResponseGetOfficesXMLResult() {
        return new GetOfficesXMLResponse.GetOfficesXMLResult();
    }

    /**
     * Create an instance of {@link GetOfficesByRegionXML }
     * 
     */
    public GetOfficesByRegionXML createGetOfficesByRegionXML() {
        return new GetOfficesByRegionXML();
    }

    /**
     * Create an instance of {@link GetOfficesByRegionXMLResponse.GetOfficesByRegionXMLResult }
     * 
     */
    public GetOfficesByRegionXMLResponse.GetOfficesByRegionXMLResult createGetOfficesByRegionXMLResponseGetOfficesByRegionXMLResult() {
        return new GetOfficesByRegionXMLResponse.GetOfficesByRegionXMLResult();
    }

    /**
     * Create an instance of {@link Data134FormFullXML }
     * 
     */
    public Data134FormFullXML createData134FormFullXML() {
        return new Data134FormFullXML();
    }

    /**
     * Create an instance of {@link Data134FormFullXMLResponse.Data134FormFullXMLResult }
     * 
     */
    public Data134FormFullXMLResponse.Data134FormFullXMLResult createData134FormFullXMLResponseData134FormFullXMLResult() {
        return new Data134FormFullXMLResponse.Data134FormFullXMLResult();
    }

    /**
     * Create an instance of {@link Olap134Form }
     * 
     */
    public Olap134Form createOlap134Form() {
        return new Olap134Form();
    }

    /**
     * Create an instance of {@link Olap134FormResponse.Olap134FormResult }
     * 
     */
    public Olap134FormResponse.Olap134FormResult createOlap134FormResponseOlap134FormResult() {
        return new Olap134FormResponse.Olap134FormResult();
    }

    /**
     * Create an instance of {@link Data135FormFull }
     * 
     */
    public Data135FormFull createData135FormFull() {
        return new Data135FormFull();
    }

    /**
     * Create an instance of {@link Data135FormFullResponse.Data135FormFullResult }
     * 
     */
    public Data135FormFullResponse.Data135FormFullResult createData135FormFullResponseData135FormFullResult() {
        return new Data135FormFullResponse.Data135FormFullResult();
    }

    /**
     * Create an instance of {@link Data135FormFullXML }
     * 
     */
    public Data135FormFullXML createData135FormFullXML() {
        return new Data135FormFullXML();
    }

    /**
     * Create an instance of {@link Data135FormFullXMLResponse.Data135FormFullXMLResult }
     * 
     */
    public Data135FormFullXMLResponse.Data135FormFullXMLResult createData135FormFullXMLResponseData135FormFullXMLResult() {
        return new Data135FormFullXMLResponse.Data135FormFullXMLResult();
    }

    /**
     * Create an instance of {@link Data123FormFull }
     * 
     */
    public Data123FormFull createData123FormFull() {
        return new Data123FormFull();
    }

    /**
     * Create an instance of {@link Data123FormFullResponse.Data123FormFullResult }
     * 
     */
    public Data123FormFullResponse.Data123FormFullResult createData123FormFullResponseData123FormFullResult() {
        return new Data123FormFullResponse.Data123FormFullResult();
    }

    /**
     * Create an instance of {@link Data123FormFullXML }
     * 
     */
    public Data123FormFullXML createData123FormFullXML() {
        return new Data123FormFullXML();
    }

    /**
     * Create an instance of {@link Data123FormFullXMLResponse.Data123FormFullXMLResult }
     * 
     */
    public Data123FormFullXMLResponse.Data123FormFullXMLResult createData123FormFullXMLResponseData123FormFullXMLResult() {
        return new Data123FormFullXMLResponse.Data123FormFullXMLResult();
    }

    /**
     * Create an instance of {@link GetDatesForF123 }
     * 
     */
    public GetDatesForF123 createGetDatesForF123() {
        return new GetDatesForF123();
    }

    /**
     * Create an instance of {@link GetDatesForF123Response }
     * 
     */
    public GetDatesForF123Response createGetDatesForF123Response() {
        return new GetDatesForF123Response();
    }

    /**
     * Create an instance of {@link ArrayOfDateTime }
     * 
     */
    public ArrayOfDateTime createArrayOfDateTime() {
        return new ArrayOfDateTime();
    }

    /**
     * Create an instance of {@link GetDatesForF101 }
     * 
     */
    public GetDatesForF101 createGetDatesForF101() {
        return new GetDatesForF101();
    }

    /**
     * Create an instance of {@link GetDatesForF101Response }
     * 
     */
    public GetDatesForF101Response createGetDatesForF101Response() {
        return new GetDatesForF101Response();
    }

    /**
     * Create an instance of {@link GetDatesForF102 }
     * 
     */
    public GetDatesForF102 createGetDatesForF102() {
        return new GetDatesForF102();
    }

    /**
     * Create an instance of {@link GetDatesForF102Response }
     * 
     */
    public GetDatesForF102Response createGetDatesForF102Response() {
        return new GetDatesForF102Response();
    }

    /**
     * Create an instance of {@link GetDatesForF134 }
     * 
     */
    public GetDatesForF134 createGetDatesForF134() {
        return new GetDatesForF134();
    }

    /**
     * Create an instance of {@link GetDatesForF134Response }
     * 
     */
    public GetDatesForF134Response createGetDatesForF134Response() {
        return new GetDatesForF134Response();
    }

    /**
     * Create an instance of {@link GetDatesForF135 }
     * 
     */
    public GetDatesForF135 createGetDatesForF135() {
        return new GetDatesForF135();
    }

    /**
     * Create an instance of {@link GetDatesForF135Response }
     * 
     */
    public GetDatesForF135Response createGetDatesForF135Response() {
        return new GetDatesForF135Response();
    }

    /**
     * Create an instance of {@link Data134FormFull }
     * 
     */
    public Data134FormFull createData134FormFull() {
        return new Data134FormFull();
    }

    /**
     * Create an instance of {@link Data134FormFullResponse.Data134FormFullResult }
     * 
     */
    public Data134FormFullResponse.Data134FormFullResult createData134FormFullResponseData134FormFullResult() {
        return new Data134FormFullResponse.Data134FormFullResult();
    }

}
