//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.08 at 09:21:29 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://web.cbr.ru/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hello.wsdl;
